[target-remote] Basic support for the `target remote` command
hugsy/gef pull request #1020
Opened 2023-12-06 17:20 UTC by ValekoZ

## Description

As mentioned in Gallopsled/pwntools#2264, gef does not work properly with many tools that rely on the `target remote` command.
In this PR, I propose a fix that uses a remote posthook in order to instantiate and setup the GefRemoteSessionManager after the connection being established.

Note that this isn't a perfect solution since we do not have all the information needed for a proper instantiation of the GefRemoteSessionManager, but it seems to be a good workaround in order to make tools like `pwntools` work correctly with gef.

2023-12-07 03:27 UTC, Grazfather reviewed
Good idea. We will want to remove the warning when using `target remote`

2023-12-07 14:32 UTC, ValekoZ commented
I'm not sure if we really want to remove the warning, since the initialization is partial (we don't initialize the `host` and `port` fields). Those fields are actually not used in the `gef` core, but if a plugin or a user wants to use them, it would probably fail :/

2023-12-07 14:33 UTC, ValekoZ commented
Oh and btw, do you want me to implement the same thing for `target extended-remote` ? I do not really know what this does, but I guess it is not that different ? I can try to check if this seems feasible

2023-12-07 17:43 UTC, Grazfather commented
1. Sure, we can move it, and adjust it, say that it's best effort or something.
2. Extended remote is just remote with more abilities, such as restarting the target and reconnecting to the server.
3. Adding it for that would be great.

2023-12-10 11:13 UTC, ValekoZ commented
I'm not sure if I broke the pipeline ? The errors do not seem to be related to my code, but apparently it appeared just after my last commit ?

2023-12-13 15:26 UTC, Grazfather commented
CI is broken because of it installing python3.12 and that changing some stuff. We will get it sorted.

Sorry for the slow work on this PR. Holiday time can be busy.

2023-12-13 21:14 UTC, Grazfather commented
If you rebase onto main after #1022 the tests should pass.

2023-12-14 01:45 UTC, hugsy requested changes
This look just great to me.

Do you mind adding a simple test (for instance in https://github.com/hugsy/gef/blob/main/tests/commands/gef_remote.py) for it?

2023-12-14 08:36 UTC, ValekoZ commented
Maybe we should add an option to disable the post-hook for those who want the default behavior ?

2023-12-14 15:31 UTC, hugsy commented
> Maybe we should add an option to disable the post-hook for those who want the default behavior ?

Probably a good idea now that you mention it.
Also validation is failing, need an empty line in gef-remote.py

2023-12-16 00:53 UTC, hugsy approved these changes
👍 , tests are passing too (ignoring the CI failure, my fault)
LGTM, thanks for your patience @ValekoZ 

I think it's ready to merge, any pending request on your end @Grazfather ?

2023-12-16 15:57 UTC, merged