Remove pyenv related code (closes #1078)
hugsy/gef pull request #1084
Opened 2024-04-13 01:37 UTC by mattzque

## Description

Removes pyenv related functionality from gef.py.

See discussion at https://github.com/hugsy/gef/issues/1078

## Checklist

-  [x] My code follows the code style of this project.
-  [ ] My change includes a change to the documentation, if required.
-  [ ] If my change adds new code, [adequate tests](docs/testing.md) have been added.
-  [x] I have read and agree to the **CONTRIBUTING** document.

2024-04-13 03:16 UTC, hugsy requested changes
That's great.

Can I ask you to add a note in the docs like [in this file](https://github.com/hugsy/gef/blob/main/docs/deprecated.md) saying `pyenv` support is dropped after 2024.05 ? 

So we don't have future PRs for adding pyenv stuff.

2024-04-14 00:45 UTC, mattzque commented
> That's great.
> 
> Can I ask you to add a note in the docs like [in this file](https://github.com/hugsy/gef/blob/main/docs/deprecated.md) saying `pyenv` support is dropped after 2024.05 ?
> 
> So we don't have future PRs for adding pyenv stuff.

Of course, I've added a note.

2024-04-14 20:11 UTC, hugsy approved these changes

2024-04-14 20:29 UTC, hugsy commented
Minor formatting issue to fix before merging

```
docs/deprecated.md:22:101 MD013/line-length Line length [Expected: 100; Actual: 215]
```

Note that you can use `pre-commit` locally to make sure you're compliant before pushing.

2024-04-15 16:14 UTC, merged