add support for hex strings to print-format
hugsy/gef pull request #758
Opened 2021-11-27 04:23 UTC by tcheinen

## add support for hex strings to print-format ##

### Description/Motivation/Screenshots ###

This patch adds an additional format to the command `print-format` -- a hex string like "00112233" instead of [0x00, 0x11, 0x22, 0x33]. I end up printing memory in another format and manually adjusting it often enough to be worth writing the code for me and I thought it was generally useful enough to PR back. I also adjusted phrasing in the documentation a little bit to signify that print format can output memory in a number of different formats, only some of which are byte array literals.  

![image](https://user-images.githubusercontent.com/1759360/143667746-d4455569-371c-4874-885e-2e85949dca2b.png)

### How Has This Been Tested? ###

| Architecture |          Yes/No          | Comments                                  |
| ------------ | :----------------------: | ----------------------------------------- |
| x86-32       | :heavy_multiplication_x: | Replace with :heavy_check_mark: if tested |
| x86-64       | :heavy_check_mark: |                                           |
| ARM          | :heavy_multiplication_x: |                                           |
| AARCH64      | :heavy_multiplication_x: |                                           |
| MIPS         | :heavy_multiplication_x: |                                           |
| POWERPC      | :heavy_multiplication_x: |                                           |
| SPARC        | :heavy_multiplication_x: |                                           |
| RISC-V       | :heavy_multiplication_x: |                                           |
| `make test`  | :heavy_check_mark: |                                           |

### Checklist ###

- [x] My PR was done against the `dev` branch, not `master`.
- [x] My code follows the code style of this project.
- [x] My change includes a change to the documentation, if required.
- [x] My change adds tests as appropriate.
- [x] I have read and agree to the **CONTRIBUTING** document.

2021-11-27 23:54 UTC, hugsy requested changes

2021-11-27 23:54 UTC, hugsy commented on gef.py
> +            out = "".join(f'{x:02x}' for x in data)
We support (for now) Python < 3.6 where f-strings don't exist. Please use the `.format` notation.

```suggestion
            out = "".join('{:02x}'.format(x) for x in data)
```

2021-11-28 04:31 UTC, hugsy approved these changes

2021-11-29 15:54 UTC, Grazfather reviewed
Forgot to submit my review.

2021-11-29 15:55 UTC, Grazfather requested changes

2021-11-29 21:44 UTC, tcheinen commented on gef.py
> +            out = "".join('{:02x}'.format(x) for x in data)
i was originally trying to go from data to hex and it didn't occur to me that I could just use read_memory directly to get the byte array. I agree hexlify is better

2021-11-29 22:01 UTC, tcheinen commented
using hexlify like this also is better bc it means the endianness is correct for bit lengths of not 8

2021-11-29 23:25 UTC, Grazfather commented on tests/runtests.py
> +        print(res)
remove

2021-11-30 00:35 UTC, Grazfather approved these changes

2021-11-30 00:38 UTC, merged