Patch pprint_dereferenced
hugsy/gef pull request #880
Opened 2022-08-04 23:21 UTC by thenetworkgrinch

The 'dereference' command errors out on MIPS32 when $fir is unavailable. 

## Description/Motivation/Screenshots

The function pprint_dereferenced errors out when a register for the supplied architecture does not exist, this patch likely needs to be fixed everywhere. Does not appear to be an issue anywhere else. Potential permanent fix would be having registers populated via the `info registers` gdb command on initialization of local and remote for the architectures.

A try catch was used as a patch, a better fix would be to use the output of `info registers` and parse it.

Context won't break if a architecture doesn't use the standard register. 

## Against which architecture was this tested ?

"Tested" indicates that the PR works *and* the unit test (i.e. `make test`) run passes without issue.

 * [ ] x86-32
 * [ ] x86-64
 * [ ] ARM
 * [ ] AARCH64
 * [ x ] MIPS        
 * [ ] POWERPC     
 * [ ] SPARC       
 * [ ] RISC-V 

## Checklist

- [ x ] My PR was done against the `dev` branch, not `main`.
- [ x ] My code follows the code style of this project.
- [ x ] My change includes a change to the documentation, if required.
- [ x ] If my change adds new code, [adequate tests](docs/testing.md) have been added.
- [ x ] I have read and agree to the **CONTRIBUTING** document.

2022-08-05 04:56 UTC, hugsy requested changes
Thanks for your PR. In this state this patch would mask any possible error happening. So as a general way we try to avoid `try/except` without specific exceptions.

`$fir` is a [required register for GDB when on MIPS](https://getdocs.org/Gdb/docs/latest/gdb/MIPS-Features). How come the register is missing in your case?

2022-08-05 05:24 UTC, thenetworkgrinch commented
I can try later today to identify further down where it errors, quick look suggests __get_register_for_selected_frame. The system is MIPS32 BE with GDB 12.0.9 over a remote connection.

2022-08-05 16:17 UTC, hugsy commented
> I can try later today to identify further down where it errors, quick look suggests __get_register_for_selected_frame. The system is MIPS32 BE with GDB 12.0.9 over a remote connection.

Great. I understand why you did your PR but knowing why it's missing here might be more helpful in order to provide a better fix (if needed).

2022-08-05 17:11 UTC, thenetworkgrinch commented
Sorry I just checked and it looks like the FPU is missing on my system when I cat `/proc/cpuinfo` which is why it is unavailable.

2022-08-05 19:49 UTC, thenetworkgrinch commented
Just changed the __get_register_for_selected_frame() function to check against the frame's registers before retrieval (satisfying previous condition where it will error if the register does not exist) while printing out the supplied error if the value cannot be converted to an integer (due to size or nonexistence).

2022-08-05 22:03 UTC, hugsy commented
> 

The FPU is missing? That seems to me like a very specific edge case. Can you post what `i r all` returns?

2022-08-05 22:04 UTC, hugsy commented
If that's really the case, your PR induces a pretty severe performance impact just to consider that case. A probably cleaner approach would be to create a new MIPS arch that inherits the original MIPS32 from GEF, but removes the `$fir` register.

2022-08-05 22:26 UTC, thenetworkgrinch commented
```
zero: 0x0
at: 0x1
v0: 0x4
... snip ...
pc: 0x77d9c960
f0:  can't read register 118 (f0)
```

2022-08-05 23:10 UTC, hugsy commented
Aside from just the `try/except`, your PR relies on API that are too recent (namely `Architecture.registers`) which is not supported in the GDB base version GEF is compatible with. Also, the function `__get_register_for_selected_frame` is called all the time. Your PR forces the call to many APIs repeatedly as they're not being cached. 
So I'm pretty sure there will be a non negligeable performance impact for all architectures when your situation seems to be an edge case. So I really think the best move is a new architecture where you remove `$fir`.

2022-08-07 18:27 UTC, thenetworkgrinch commented
Thank you for the explanation! That makes alot of sense and I will do a PR for the Arch later.

2022-08-07 18:27 UTC, closed without merging