Fix searching when connected to `qemu-system` instance
hugsy/gef pull request #906
Opened 2022-10-22 14:54 UTC by clubby789

## Description/Motivation/Screenshots

Fixes #905 
Detects when we're connected to a QEMU kernel instance, and uses `monitor info mem` to retrieve the real kernel memory mappings for searching within.

## Against which architecture was this tested ?

"Tested" indicates that the PR works *and* the unit test (see `docs/testing.md`) run passes without issue.

 * [ ] x86-32
 * [X ] x86-64
 * [ ] ARM
 * [ ] AARCH64
 * [ ] MIPS
 * [ ] POWERPC
 * [ ] SPARC
 * [ ] RISC-V

## Checklist

- [X] My PR was done against the `dev` branch, not `main`.
- [X] My code follows the code style of this project.
- [X] My change includes a change to the documentation, if required.
- [ ] If my change adds new code, [adequate tests](docs/testing.md) have been added.
- [X] I have read and agree to the **CONTRIBUTING** document.

I will add tests shortly, just leaving this initial draft.

2022-10-22 15:26 UTC, clubby789 commented
I noticed that the code for detecting if we're in a qemu/qemu-system context already exists, so I've removed my duplicated code. The code added is mainly just invoking and parsing `monitor info mem`, and using those memory mappings when needed. As there is currently no testing harness for `qemu-system`, I haven't added tests.

2022-10-22 16:23 UTC, clubby789 commented
Because of a typo (`QOffsets` -> `qOffsets`), `qemu` sessions would always be identified as kernel-mode. All tests look good locally now

2022-10-24 16:08 UTC, clubby789 commented
As a side note, it looks like the search command buffers the output til completion. Having it print as items are discovered (or at least having that as an option) would help when the search takes a long time (i.e. traversing the large memory space of the kernel)

2022-10-28 01:39 UTC, Grazfather commented
Looks good, a few comments, and I'll have to figure out how to test it.

> As a side note, it looks like the search command buffers the output til completion. Having it print as items are discovered (or at least having that as an option) would help when the search takes a long time (i.e. traversing the large memory space of the kernel)

Yes, good call. Go ahead and file a ticket if you don't mind.

2022-10-29 14:08 UTC, Grazfather reviewed
Forgot to submit my review.

2022-10-29 14:59 UTC, clubby789 commented on gef.py
> +    def from_info_mem(perm_str: str) -> "Permission":
I just copied the style of the other parser functions - should they be updated like that as well?

2022-10-29 15:01 UTC, Grazfather commented on gef.py
> +    def from_info_mem(perm_str: str) -> "Permission":
Ah, I see that. They should be. If you could update them I'd appreciate it. See [here](https://dev.to/p0intman/alternative-constructors-in-python-58gb)

2022-10-29 15:13 UTC, Grazfather approved these changes
Looks good, just more nitpicking.

2022-10-29 15:13 UTC, Grazfather commented on gef.py
> +    response = gdb.execute('maintenance packet qOffsets', to_string=True, from_tty=False)
double quotes here, even if it was wrong in the first place :)

2022-10-29 15:13 UTC, Grazfather commented on gef.py
> -    response = gdb.execute('maintenance packet QOffsets', to_string=True, from_tty=False)
`"`

2022-11-17 04:30 UTC, hugsy commented on gef.py
> +        gef.session.remote = False
Great catch on this! Totally miss this bug!
However, I'm not super fan of this approach (setting it to False) as it introduces a type error. There could be different approaches, not very costly: probably the easiest would to add a state to `GefRemoteSessionManager` (or even just a boolean like `initialized`) that we could check from the outside.

2022-11-17 04:32 UTC, hugsy commented on gef.py
> +        gef.session.remote = False
Actually considering the remote nature of the manager, yeah a small state attribute could definitely be useful but for this PR, maybe just `initialized` set or something could work.

2022-11-17 04:55 UTC, hugsy requested changes
Another great PR @clubby789 , again some small stuff to fix.

2022-11-17 04:55 UTC, hugsy commented on gef.py
> +        for line in stream:
```suggestion
        for line in StringIO(gdb.execute("monitor info mem", to_string=True)):
```

2022-11-17 04:55 UTC, hugsy commented on gef.py
> +        for line in stream:
Note: I know I did the same in the function above, but might as well improve what we can now 😊

2022-11-17 04:55 UTC, hugsy commented on gef.py
> +                ranges, off, perms = line.split(" ")
```suggestion
                ranges, off, perms = line.split()
```

2022-11-17 04:55 UTC, hugsy commented on gef.py
> +                # `perms` are `urw`, for "usermode", "readable", "writable"
Not convinced of the value of the comment here: probably better in a CI test for this function.

```suggestion
```

2022-11-17 04:55 UTC, hugsy commented on gef.py
> +                return list(self.__parse_info_mem())
Awesome stuff

2022-11-17 04:56 UTC, hugsy commented
BTW you should be able to merge the latest changes from `dev`, the CI tests should run again successfully on your next push.

Cheers!

2022-11-17 14:18 UTC, clubby789 commented
Tests look okay locally and on Ubuntu 20, probably random failure?

2022-11-18 19:50 UTC, hugsy commented
@clubby789 
Your changes look good, go ahead and merge the latest changes from dev. I believe all tests should pass now, then I'll go ahead and merge your PR.

2022-11-23 05:16 UTC, hugsy approved these changes

2022-11-23 05:16 UTC, merged