Remove outdated sentence in docs
hugsy/gef pull request #948
Opened 2023-04-20 06:18 UTC by bkrl

## Description/Motivation/Screenshots

I removed a sentence on the home page which states that GEF supports both Python 2 and Python 3 since Python 2 is no longer supported.

## Checklist

- [x] My PR was done against the `dev` branch, not `main`.
- [x] My code follows the code style of this project.
- [x] My change includes a change to the documentation, if required.
- [x] If my change adds new code, [adequate tests](docs/testing.md) have been added.
- [x] I have read and agree to the **CONTRIBUTING** document.

2023-04-22 14:51 UTC, hugsy requested changes

2023-04-22 14:51 UTC, hugsy commented on docs/index.md
> -It has full support for both Python2 and Python3 indifferently (as more and more
Good catch but instead of removing the sentence altogether, I'd prefer if you leave the part mentioning Python3 support, and for people stuck with old versions of gdb + py2 to turn to GEF-Legacy. This was done in other places of the docs

2023-04-25 06:50 UTC, bkrl commented on docs/index.md
> -It has full support for both Python2 and Python3 indifferently (as more and more
Done.

2023-04-25 15:55 UTC, hugsy approved these changes

2023-04-25 15:56 UTC, merged